# Generated by Django 5.2.7 on 2025-12-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='clubs',
            field=models.ManyToManyField(blank=True, related_name='members', to='app.club'),
        ),
    ]
