# Generated by Django 5.2.7 on 2025-12-15 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_club_followers_post_club'),
        ('app', '0006_profile_clubs'),
    ]

    operations = [
    ]
