# Generated by Django 5.2.7 on 2025-12-15 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_20251214_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='post',
            name='club',
        ),
    ]
